version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 25
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - cloud.google.com/go/spanner
            - github.com/cccteam
            - github.com/coreos/go-oidc/v3
            - github.com/georgysavva/scany/v2
            - github.com/go-chi/chi/v5
            - github.com/go-playground/errors/v5
            - github.com/gofrs/uuid
            - github.com/google/go-cmp
            - github.com/gorilla/securecookie
            - github.com/jackc/pgx/v5
            - go.opentelemetry.io/otel
            - go.uber.org/mock
            - golang.org/x/oauth2
            - google.golang.org/grpc/codes
            - $gostd
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    godox:
      keywords:
        - TODO
        - BUG
    lll:
      line-length: 200
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .Cause(
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocyclo
          - lll
          - mnd
          - nlreturn
          - scopelint
        path: _test\.go
      - linters:
          - tagliatelle
        path: oidc\.go|oidc_skipAuth\.go
        text: preferred_username
      - linters:
          - gomoddirectives
        path: go\.mod
        text: replacement are not allowed
      - linters:
          - revive
        text: avoid meaningless package names
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
