// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/basesession/basesession_iface.go
//
// Generated by this command:
//
//	mockgen -source ../internal/basesession/basesession_iface.go -destination mock_basesession/mock_basesession_iface.go
//

// Package mock_basesession is a generated GoMock package.
package mock_basesession

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// Authenticated mocks base method.
func (m *MockHandlers) Authenticated() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticated")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Authenticated indicates an expected call of Authenticated.
func (mr *MockHandlersMockRecorder) Authenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticated", reflect.TypeOf((*MockHandlers)(nil).Authenticated))
}

// Logout mocks base method.
func (m *MockHandlers) Logout() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockHandlersMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockHandlers)(nil).Logout))
}

// SetXSRFToken mocks base method.
func (m *MockHandlers) SetXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetXSRFToken indicates an expected call of SetXSRFToken.
func (mr *MockHandlersMockRecorder) SetXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXSRFToken", reflect.TypeOf((*MockHandlers)(nil).SetXSRFToken), next)
}

// StartSession mocks base method.
func (m *MockHandlers) StartSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// StartSession indicates an expected call of StartSession.
func (mr *MockHandlersMockRecorder) StartSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockHandlers)(nil).StartSession), next)
}

// ValidateSession mocks base method.
func (m *MockHandlers) ValidateSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockHandlersMockRecorder) ValidateSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockHandlers)(nil).ValidateSession), next)
}

// ValidateXSRFToken mocks base method.
func (m *MockHandlers) ValidateXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateXSRFToken indicates an expected call of ValidateXSRFToken.
func (mr *MockHandlersMockRecorder) ValidateXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateXSRFToken", reflect.TypeOf((*MockHandlers)(nil).ValidateXSRFToken), next)
}
