// Code generated by MockGen. DO NOT EDIT.
// Source: ../sessionstorage/accounts.go
//
// Generated by this command:
//
//	mockgen -source ../sessionstorage/accounts.go -destination ../sessionstorage/mock/mock_sessionstorage/mock_accounts.go -package mock_sessionstorage -aux_files github.com/cccteam/session/sessionstorage=../sessionstorage/sessionstorage_iface.go
//

// Package mock_sessionstorage is a generated GoMock package.
package mock_sessionstorage

import (
	context "context"
	reflect "reflect"
	time "time"

	ccc "github.com/cccteam/ccc"
	securehash "github.com/cccteam/ccc/securehash"
	sessioninfo "github.com/cccteam/session/sessioninfo"
	sessionstorage "github.com/cccteam/session/sessionstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountStore is a mock of AccountStore interface.
type MockAccountStore struct {
	ctrl     *gomock.Controller
	recorder *MockAccountStoreMockRecorder
	isgomock struct{}
}

// MockAccountStoreMockRecorder is the mock recorder for MockAccountStore.
type MockAccountStoreMockRecorder struct {
	mock *MockAccountStore
}

// NewMockAccountStore creates a new mock instance.
func NewMockAccountStore(ctrl *gomock.Controller) *MockAccountStore {
	mock := &MockAccountStore{ctrl: ctrl}
	mock.recorder = &MockAccountStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountStore) EXPECT() *MockAccountStoreMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockAccountStore) ActivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockAccountStoreMockRecorder) ActivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockAccountStore)(nil).ActivateUser), ctx, id)
}

// ActiveImpersonations mocks base method.
func (m *MockAccountStore) ActiveImpersonations(ctx context.Context, activeSince time.Time, q *sessioninfo.ImpersonationQuery) ([]*sessioninfo.Impersonation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveImpersonations", ctx, activeSince, q)
	ret0, _ := ret[0].([]*sessioninfo.Impersonation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveImpersonations indicates an expected call of ActiveImpersonations.
func (mr *MockAccountStoreMockRecorder) ActiveImpersonations(ctx, activeSince, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveImpersonations", reflect.TypeOf((*MockAccountStore)(nil).ActiveImpersonations), ctx, activeSince, q)
}

// AppendAuthEvent mocks base method.
func (m *MockAccountStore) AppendAuthEvent(ctx context.Context, sessionID ccc.UUID, event *sessioninfo.AuthEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAuthEvent", ctx, sessionID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAuthEvent indicates an expected call of AppendAuthEvent.
func (mr *MockAccountStoreMockRecorder) AppendAuthEvent(ctx, sessionID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAuthEvent", reflect.TypeOf((*MockAccountStore)(nil).AppendAuthEvent), ctx, sessionID, event)
}

// CreateImpersonatedSession mocks base method.
func (m *MockAccountStore) CreateImpersonatedSession(ctx context.Context, req *sessioninfo.NewSessionRequest, imp *sessioninfo.Impersonation) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImpersonatedSession", ctx, req, imp)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImpersonatedSession indicates an expected call of CreateImpersonatedSession.
func (mr *MockAccountStoreMockRecorder) CreateImpersonatedSession(ctx, req, imp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImpersonatedSession", reflect.TypeOf((*MockAccountStore)(nil).CreateImpersonatedSession), ctx, req, imp)
}

// CreateSession mocks base method.
func (m *MockAccountStore) CreateSession(ctx context.Context, req *sessioninfo.NewSessionRequest) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAccountStoreMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAccountStore)(nil).CreateSession), ctx, req)
}

// CreateUser mocks base method.
func (m *MockAccountStore) CreateUser(ctx context.Context, user *sessionstorage.InsertSessionUser, customData any) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user, customData)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAccountStoreMockRecorder) CreateUser(ctx, user, customData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAccountStore)(nil).CreateUser), ctx, user, customData)
}

// CustomDataType mocks base method.
func (m *MockAccountStore) CustomDataType() reflect.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomDataType")
	ret0, _ := ret[0].(reflect.Type)
	return ret0
}

// CustomDataType indicates an expected call of CustomDataType.
func (mr *MockAccountStoreMockRecorder) CustomDataType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomDataType", reflect.TypeOf((*MockAccountStore)(nil).CustomDataType))
}

// CustomUserData mocks base method.
func (m *MockAccountStore) CustomUserData(ctx context.Context, userID ccc.UUID) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomUserData", ctx, userID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomUserData indicates an expected call of CustomUserData.
func (mr *MockAccountStoreMockRecorder) CustomUserData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomUserData", reflect.TypeOf((*MockAccountStore)(nil).CustomUserData), ctx, userID)
}

// CustomUserDataType mocks base method.
func (m *MockAccountStore) CustomUserDataType() reflect.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomUserDataType")
	ret0, _ := ret[0].(reflect.Type)
	return ret0
}

// CustomUserDataType indicates an expected call of CustomUserDataType.
func (mr *MockAccountStoreMockRecorder) CustomUserDataType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomUserDataType", reflect.TypeOf((*MockAccountStore)(nil).CustomUserDataType))
}

// DeactivateUser mocks base method.
func (m *MockAccountStore) DeactivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockAccountStoreMockRecorder) DeactivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockAccountStore)(nil).DeactivateUser), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockAccountStore) DeleteUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAccountStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAccountStore)(nil).DeleteUser), ctx, id)
}

// DestroyAllUserSessions mocks base method.
func (m *MockAccountStore) DestroyAllUserSessions(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyAllUserSessions", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyAllUserSessions indicates an expected call of DestroyAllUserSessions.
func (mr *MockAccountStoreMockRecorder) DestroyAllUserSessions(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyAllUserSessions", reflect.TypeOf((*MockAccountStore)(nil).DestroyAllUserSessions), ctx, username)
}

// DestroyImpersonatedSession mocks base method.
func (m *MockAccountStore) DestroyImpersonatedSession(ctx context.Context, sessionID ccc.UUID, reason sessioninfo.ImpersonationEndReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyImpersonatedSession", ctx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyImpersonatedSession indicates an expected call of DestroyImpersonatedSession.
func (mr *MockAccountStoreMockRecorder) DestroyImpersonatedSession(ctx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyImpersonatedSession", reflect.TypeOf((*MockAccountStore)(nil).DestroyImpersonatedSession), ctx, sessionID, reason)
}

// DestroyImpersonatedSessions mocks base method.
func (m *MockAccountStore) DestroyImpersonatedSessions(ctx context.Context, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyImpersonatedSessions", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyImpersonatedSessions indicates an expected call of DestroyImpersonatedSessions.
func (mr *MockAccountStoreMockRecorder) DestroyImpersonatedSessions(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyImpersonatedSessions", reflect.TypeOf((*MockAccountStore)(nil).DestroyImpersonatedSessions), ctx, actor)
}

// DestroySession mocks base method.
func (m *MockAccountStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockAccountStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockAccountStore)(nil).DestroySession), ctx, sessionID)
}

// DestroyUserSessions mocks base method.
func (m *MockAccountStore) DestroyUserSessions(ctx context.Context, userID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyUserSessions indicates an expected call of DestroyUserSessions.
func (mr *MockAccountStoreMockRecorder) DestroyUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyUserSessions", reflect.TypeOf((*MockAccountStore)(nil).DestroyUserSessions), ctx, userID)
}

// EndImpersonation mocks base method.
func (m *MockAccountStore) EndImpersonation(ctx context.Context, sessionID ccc.UUID, reason sessioninfo.ImpersonationEndReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndImpersonation", ctx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndImpersonation indicates an expected call of EndImpersonation.
func (mr *MockAccountStoreMockRecorder) EndImpersonation(ctx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndImpersonation", reflect.TypeOf((*MockAccountStore)(nil).EndImpersonation), ctx, sessionID, reason)
}

// IdentitiesByUser mocks base method.
func (m *MockAccountStore) IdentitiesByUser(ctx context.Context, userID ccc.UUID) ([]*sessionstorage.SessionIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentitiesByUser", ctx, userID)
	ret0, _ := ret[0].([]*sessionstorage.SessionIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentitiesByUser indicates an expected call of IdentitiesByUser.
func (mr *MockAccountStoreMockRecorder) IdentitiesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentitiesByUser", reflect.TypeOf((*MockAccountStore)(nil).IdentitiesByUser), ctx, userID)
}

// IdentitiesEnabled mocks base method.
func (m *MockAccountStore) IdentitiesEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentitiesEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IdentitiesEnabled indicates an expected call of IdentitiesEnabled.
func (mr *MockAccountStoreMockRecorder) IdentitiesEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentitiesEnabled", reflect.TypeOf((*MockAccountStore)(nil).IdentitiesEnabled))
}

// Identity mocks base method.
func (m *MockAccountStore) Identity(ctx context.Context, method sessioninfo.AuthMethod, connection, subject string) (*sessionstorage.SessionIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identity", ctx, method, connection, subject)
	ret0, _ := ret[0].(*sessionstorage.SessionIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Identity indicates an expected call of Identity.
func (mr *MockAccountStoreMockRecorder) Identity(ctx, method, connection, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identity", reflect.TypeOf((*MockAccountStore)(nil).Identity), ctx, method, connection, subject)
}

// ImpersonationEnabled mocks base method.
func (m *MockAccountStore) ImpersonationEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImpersonationEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ImpersonationEnabled indicates an expected call of ImpersonationEnabled.
func (mr *MockAccountStoreMockRecorder) ImpersonationEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImpersonationEnabled", reflect.TypeOf((*MockAccountStore)(nil).ImpersonationEnabled))
}

// LinkIdentity mocks base method.
func (m *MockAccountStore) LinkIdentity(ctx context.Context, userID ccc.UUID, identity *sessioninfo.Identity, tenant string) (*sessionstorage.SessionIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkIdentity", ctx, userID, identity, tenant)
	ret0, _ := ret[0].(*sessionstorage.SessionIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkIdentity indicates an expected call of LinkIdentity.
func (mr *MockAccountStoreMockRecorder) LinkIdentity(ctx, userID, identity, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkIdentity", reflect.TypeOf((*MockAccountStore)(nil).LinkIdentity), ctx, userID, identity, tenant)
}

// NewSession mocks base method.
func (m *MockAccountStore) NewSession(ctx context.Context, username string, customData any) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username, customData)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockAccountStoreMockRecorder) NewSession(ctx, username, customData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockAccountStore)(nil).NewSession), ctx, username, customData)
}

// OIDCUsersEnabled mocks base method.
func (m *MockAccountStore) OIDCUsersEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCUsersEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// OIDCUsersEnabled indicates an expected call of OIDCUsersEnabled.
func (mr *MockAccountStoreMockRecorder) OIDCUsersEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCUsersEnabled", reflect.TypeOf((*MockAccountStore)(nil).OIDCUsersEnabled))
}

// Session mocks base method.
func (m *MockAccountStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockAccountStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockAccountStore)(nil).Session), ctx, sessionID)
}

// SetOIDCUserTableName mocks base method.
func (m *MockAccountStore) SetOIDCUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOIDCUserTableName", name)
}

// SetOIDCUserTableName indicates an expected call of SetOIDCUserTableName.
func (mr *MockAccountStoreMockRecorder) SetOIDCUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOIDCUserTableName", reflect.TypeOf((*MockAccountStore)(nil).SetOIDCUserTableName), name)
}

// SetSessionTableName mocks base method.
func (m *MockAccountStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockAccountStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockAccountStore)(nil).SetSessionTableName), name)
}

// SetUserPasswordHash mocks base method.
func (m *MockAccountStore) SetUserPasswordHash(ctx context.Context, id ccc.UUID, hash *securehash.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserPasswordHash indicates an expected call of SetUserPasswordHash.
func (mr *MockAccountStoreMockRecorder) SetUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPasswordHash", reflect.TypeOf((*MockAccountStore)(nil).SetUserPasswordHash), ctx, id, hash)
}

// SetUserTableName mocks base method.
func (m *MockAccountStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockAccountStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockAccountStore)(nil).SetUserTableName), name)
}

// SetUserUsername mocks base method.
func (m *MockAccountStore) SetUserUsername(ctx context.Context, id ccc.UUID, newUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserUsername", ctx, id, newUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserUsername indicates an expected call of SetUserUsername.
func (mr *MockAccountStoreMockRecorder) SetUserUsername(ctx, id, newUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserUsername", reflect.TypeOf((*MockAccountStore)(nil).SetUserUsername), ctx, id, newUsername)
}

// UnlinkIdentity mocks base method.
func (m *MockAccountStore) UnlinkIdentity(ctx context.Context, identityID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkIdentity", ctx, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkIdentity indicates an expected call of UnlinkIdentity.
func (mr *MockAccountStoreMockRecorder) UnlinkIdentity(ctx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkIdentity", reflect.TypeOf((*MockAccountStore)(nil).UnlinkIdentity), ctx, identityID)
}

// UpdateCustomSessionData mocks base method.
func (m *MockAccountStore) UpdateCustomSessionData(ctx context.Context, sessionID ccc.UUID, mutate func(any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomSessionData", ctx, sessionID, mutate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomSessionData indicates an expected call of UpdateCustomSessionData.
func (mr *MockAccountStoreMockRecorder) UpdateCustomSessionData(ctx, sessionID, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomSessionData", reflect.TypeOf((*MockAccountStore)(nil).UpdateCustomSessionData), ctx, sessionID, mutate)
}

// UpdateCustomUserData mocks base method.
func (m *MockAccountStore) UpdateCustomUserData(ctx context.Context, userID ccc.UUID, mutate func(any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomUserData", ctx, userID, mutate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomUserData indicates an expected call of UpdateCustomUserData.
func (mr *MockAccountStoreMockRecorder) UpdateCustomUserData(ctx, userID, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomUserData", reflect.TypeOf((*MockAccountStore)(nil).UpdateCustomUserData), ctx, userID, mutate)
}

// UpdateSessionActivity mocks base method.
func (m *MockAccountStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockAccountStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockAccountStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// User mocks base method.
func (m *MockAccountStore) User(ctx context.Context, id ccc.UUID) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockAccountStoreMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockAccountStore)(nil).User), ctx, id)
}

// UserByUserName mocks base method.
func (m *MockAccountStore) UserByUserName(ctx context.Context, username string) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUserName", ctx, username)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUserName indicates an expected call of UserByUserName.
func (mr *MockAccountStoreMockRecorder) UserByUserName(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUserName", reflect.TypeOf((*MockAccountStore)(nil).UserByUserName), ctx, username)
}

// UserDataLoginHookConfigured mocks base method.
func (m *MockAccountStore) UserDataLoginHookConfigured() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDataLoginHookConfigured")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UserDataLoginHookConfigured indicates an expected call of UserDataLoginHookConfigured.
func (mr *MockAccountStoreMockRecorder) UserDataLoginHookConfigured() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDataLoginHookConfigured", reflect.TypeOf((*MockAccountStore)(nil).UserDataLoginHookConfigured))
}
