// Code generated by MockGen. DO NOT EDIT.
// Source: ../sessionstorage/sessionstorage_iface.go
//
// Generated by this command:
//
//	mockgen -source ../sessionstorage/sessionstorage_iface.go -destination ../sessionstorage/mock/mock_sessionstorage/mock_sessionstorage.go -exclude_interfaces db
//

// Package mock_sessionstorage is a generated GoMock package.
package mock_sessionstorage

import (
	context "context"
	reflect "reflect"

	ccc "github.com/cccteam/ccc"
	securehash "github.com/cccteam/ccc/securehash"
	sessioninfo "github.com/cccteam/session/sessioninfo"
	sessionstorage "github.com/cccteam/session/sessionstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockBaseStore is a mock of BaseStore interface.
type MockBaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockBaseStoreMockRecorder
	isgomock struct{}
}

// MockBaseStoreMockRecorder is the mock recorder for MockBaseStore.
type MockBaseStoreMockRecorder struct {
	mock *MockBaseStore
}

// NewMockBaseStore creates a new mock instance.
func NewMockBaseStore(ctrl *gomock.Controller) *MockBaseStore {
	mock := &MockBaseStore{ctrl: ctrl}
	mock.recorder = &MockBaseStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseStore) EXPECT() *MockBaseStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockBaseStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockBaseStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockBaseStore)(nil).DestroySession), ctx, sessionID)
}

// Session mocks base method.
func (m *MockBaseStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockBaseStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockBaseStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockBaseStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockBaseStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockBaseStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockBaseStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockBaseStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockBaseStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockBaseStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockBaseStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockBaseStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// MockPreauthStore is a mock of PreauthStore interface.
type MockPreauthStore struct {
	ctrl     *gomock.Controller
	recorder *MockPreauthStoreMockRecorder
	isgomock struct{}
}

// MockPreauthStoreMockRecorder is the mock recorder for MockPreauthStore.
type MockPreauthStoreMockRecorder struct {
	mock *MockPreauthStore
}

// NewMockPreauthStore creates a new mock instance.
func NewMockPreauthStore(ctrl *gomock.Controller) *MockPreauthStore {
	mock := &MockPreauthStore{ctrl: ctrl}
	mock.recorder = &MockPreauthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreauthStore) EXPECT() *MockPreauthStoreMockRecorder {
	return m.recorder
}

// DestroyAllUserSessions mocks base method.
func (m *MockPreauthStore) DestroyAllUserSessions(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyAllUserSessions", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyAllUserSessions indicates an expected call of DestroyAllUserSessions.
func (mr *MockPreauthStoreMockRecorder) DestroyAllUserSessions(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyAllUserSessions", reflect.TypeOf((*MockPreauthStore)(nil).DestroyAllUserSessions), ctx, username)
}

// DestroySession mocks base method.
func (m *MockPreauthStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockPreauthStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockPreauthStore)(nil).DestroySession), ctx, sessionID)
}

// NewSession mocks base method.
func (m *MockPreauthStore) NewSession(ctx context.Context, username string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockPreauthStoreMockRecorder) NewSession(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockPreauthStore)(nil).NewSession), ctx, username)
}

// Session mocks base method.
func (m *MockPreauthStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockPreauthStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockPreauthStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockPreauthStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockPreauthStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockPreauthStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockPreauthStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockPreauthStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockPreauthStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockPreauthStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockPreauthStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockPreauthStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// MockPasswordAuthStore is a mock of PasswordAuthStore interface.
type MockPasswordAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordAuthStoreMockRecorder
	isgomock struct{}
}

// MockPasswordAuthStoreMockRecorder is the mock recorder for MockPasswordAuthStore.
type MockPasswordAuthStoreMockRecorder struct {
	mock *MockPasswordAuthStore
}

// NewMockPasswordAuthStore creates a new mock instance.
func NewMockPasswordAuthStore(ctrl *gomock.Controller) *MockPasswordAuthStore {
	mock := &MockPasswordAuthStore{ctrl: ctrl}
	mock.recorder = &MockPasswordAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordAuthStore) EXPECT() *MockPasswordAuthStoreMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockPasswordAuthStore) ActivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockPasswordAuthStoreMockRecorder) ActivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockPasswordAuthStore)(nil).ActivateUser), ctx, id)
}

// CreateSession mocks base method.
func (m *MockPasswordAuthStore) CreateSession(ctx context.Context, req sessioninfo.NewSessionRequest) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockPasswordAuthStoreMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockPasswordAuthStore)(nil).CreateSession), ctx, req)
}

// CreateUser mocks base method.
func (m *MockPasswordAuthStore) CreateUser(ctx context.Context, user *sessionstorage.InsertSessionUser) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockPasswordAuthStoreMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockPasswordAuthStore)(nil).CreateUser), ctx, user)
}

// DeactivateUser mocks base method.
func (m *MockPasswordAuthStore) DeactivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockPasswordAuthStoreMockRecorder) DeactivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockPasswordAuthStore)(nil).DeactivateUser), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockPasswordAuthStore) DeleteUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockPasswordAuthStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockPasswordAuthStore)(nil).DeleteUser), ctx, id)
}

// DestroyAllUserSessions mocks base method.
func (m *MockPasswordAuthStore) DestroyAllUserSessions(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyAllUserSessions", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyAllUserSessions indicates an expected call of DestroyAllUserSessions.
func (mr *MockPasswordAuthStoreMockRecorder) DestroyAllUserSessions(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyAllUserSessions", reflect.TypeOf((*MockPasswordAuthStore)(nil).DestroyAllUserSessions), ctx, username)
}

// DestroySession mocks base method.
func (m *MockPasswordAuthStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockPasswordAuthStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockPasswordAuthStore)(nil).DestroySession), ctx, sessionID)
}

// NewSession mocks base method.
func (m *MockPasswordAuthStore) NewSession(ctx context.Context, username string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockPasswordAuthStoreMockRecorder) NewSession(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockPasswordAuthStore)(nil).NewSession), ctx, username)
}

// Session mocks base method.
func (m *MockPasswordAuthStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockPasswordAuthStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockPasswordAuthStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockPasswordAuthStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockPasswordAuthStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockPasswordAuthStore)(nil).SetSessionTableName), name)
}

// SetUserPasswordHash mocks base method.
func (m *MockPasswordAuthStore) SetUserPasswordHash(ctx context.Context, id ccc.UUID, hash *securehash.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserPasswordHash indicates an expected call of SetUserPasswordHash.
func (mr *MockPasswordAuthStoreMockRecorder) SetUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPasswordHash", reflect.TypeOf((*MockPasswordAuthStore)(nil).SetUserPasswordHash), ctx, id, hash)
}

// SetUserTableName mocks base method.
func (m *MockPasswordAuthStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockPasswordAuthStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockPasswordAuthStore)(nil).SetUserTableName), name)
}

// SetUserUsername mocks base method.
func (m *MockPasswordAuthStore) SetUserUsername(ctx context.Context, id ccc.UUID, newUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserUsername", ctx, id, newUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserUsername indicates an expected call of SetUserUsername.
func (mr *MockPasswordAuthStoreMockRecorder) SetUserUsername(ctx, id, newUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserUsername", reflect.TypeOf((*MockPasswordAuthStore)(nil).SetUserUsername), ctx, id, newUsername)
}

// UpdateCustomSessionData mocks base method.
func (m *MockPasswordAuthStore) UpdateCustomSessionData(ctx context.Context, sessionID ccc.UUID, customData ...*sessioninfo.CustomData) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sessionID}
	for _, a := range customData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCustomSessionData", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomSessionData indicates an expected call of UpdateCustomSessionData.
func (mr *MockPasswordAuthStoreMockRecorder) UpdateCustomSessionData(ctx, sessionID any, customData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sessionID}, customData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomSessionData", reflect.TypeOf((*MockPasswordAuthStore)(nil).UpdateCustomSessionData), varargs...)
}

// UpdateSessionActivity mocks base method.
func (m *MockPasswordAuthStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockPasswordAuthStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockPasswordAuthStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// User mocks base method.
func (m *MockPasswordAuthStore) User(ctx context.Context, id ccc.UUID) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockPasswordAuthStoreMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockPasswordAuthStore)(nil).User), ctx, id)
}

// UserByUserName mocks base method.
func (m *MockPasswordAuthStore) UserByUserName(ctx context.Context, username string) (*sessionstorage.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUserName", ctx, username)
	ret0, _ := ret[0].(*sessionstorage.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUserName indicates an expected call of UserByUserName.
func (mr *MockPasswordAuthStoreMockRecorder) UserByUserName(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUserName", reflect.TypeOf((*MockPasswordAuthStore)(nil).UserByUserName), ctx, username)
}

// MockOIDCStore is a mock of OIDCStore interface.
type MockOIDCStore struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCStoreMockRecorder
	isgomock struct{}
}

// MockOIDCStoreMockRecorder is the mock recorder for MockOIDCStore.
type MockOIDCStoreMockRecorder struct {
	mock *MockOIDCStore
}

// NewMockOIDCStore creates a new mock instance.
func NewMockOIDCStore(ctrl *gomock.Controller) *MockOIDCStore {
	mock := &MockOIDCStore{ctrl: ctrl}
	mock.recorder = &MockOIDCStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCStore) EXPECT() *MockOIDCStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockOIDCStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockOIDCStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockOIDCStore)(nil).DestroySession), ctx, sessionID)
}

// DestroySessionOIDC mocks base method.
func (m *MockOIDCStore) DestroySessionOIDC(ctx context.Context, oidcSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySessionOIDC", ctx, oidcSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySessionOIDC indicates an expected call of DestroySessionOIDC.
func (mr *MockOIDCStoreMockRecorder) DestroySessionOIDC(ctx, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySessionOIDC", reflect.TypeOf((*MockOIDCStore)(nil).DestroySessionOIDC), ctx, oidcSID)
}

// NewSession mocks base method.
func (m *MockOIDCStore) NewSession(ctx context.Context, username, oidcSID string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username, oidcSID)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockOIDCStoreMockRecorder) NewSession(ctx, username, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockOIDCStore)(nil).NewSession), ctx, username, oidcSID)
}

// Session mocks base method.
func (m *MockOIDCStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockOIDCStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockOIDCStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockOIDCStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockOIDCStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockOIDCStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockOIDCStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockOIDCStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockOIDCStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockOIDCStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockOIDCStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockOIDCStore)(nil).UpdateSessionActivity), ctx, sessionID)
}
