// Code generated by MockGen. DO NOT EDIT.
// Source: ../sessionstorage/sessionstorage_iface.go
//
// Generated by this command:
//
//	mockgen -source ../sessionstorage/sessionstorage_iface.go -destination ../sessionstorage/mock/mock_sessionstorage/mock_sessionstorage.go
//

// Package mock_sessionstorage is a generated GoMock package.
package mock_sessionstorage

import (
	context "context"
	reflect "reflect"

	ccc "github.com/cccteam/ccc"
	securehash "github.com/cccteam/ccc/securehash"
	sessioninfo "github.com/cccteam/session/sessioninfo"
	dbtype "github.com/cccteam/session/sessionstorage/internal/dbtype"
	gomock "go.uber.org/mock/gomock"
)

// MockBaseStore is a mock of BaseStore interface.
type MockBaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockBaseStoreMockRecorder
	isgomock struct{}
}

// MockBaseStoreMockRecorder is the mock recorder for MockBaseStore.
type MockBaseStoreMockRecorder struct {
	mock *MockBaseStore
}

// NewMockBaseStore creates a new mock instance.
func NewMockBaseStore(ctrl *gomock.Controller) *MockBaseStore {
	mock := &MockBaseStore{ctrl: ctrl}
	mock.recorder = &MockBaseStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseStore) EXPECT() *MockBaseStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockBaseStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockBaseStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockBaseStore)(nil).DestroySession), ctx, sessionID)
}

// Session mocks base method.
func (m *MockBaseStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockBaseStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockBaseStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockBaseStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockBaseStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockBaseStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockBaseStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockBaseStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockBaseStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockBaseStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockBaseStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockBaseStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// MockPreauthStore is a mock of PreauthStore interface.
type MockPreauthStore struct {
	ctrl     *gomock.Controller
	recorder *MockPreauthStoreMockRecorder
	isgomock struct{}
}

// MockPreauthStoreMockRecorder is the mock recorder for MockPreauthStore.
type MockPreauthStoreMockRecorder struct {
	mock *MockPreauthStore
}

// NewMockPreauthStore creates a new mock instance.
func NewMockPreauthStore(ctrl *gomock.Controller) *MockPreauthStore {
	mock := &MockPreauthStore{ctrl: ctrl}
	mock.recorder = &MockPreauthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreauthStore) EXPECT() *MockPreauthStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockPreauthStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockPreauthStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockPreauthStore)(nil).DestroySession), ctx, sessionID)
}

// NewSession mocks base method.
func (m *MockPreauthStore) NewSession(ctx context.Context, username string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockPreauthStoreMockRecorder) NewSession(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockPreauthStore)(nil).NewSession), ctx, username)
}

// Session mocks base method.
func (m *MockPreauthStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockPreauthStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockPreauthStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockPreauthStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockPreauthStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockPreauthStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockPreauthStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockPreauthStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockPreauthStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockPreauthStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockPreauthStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockPreauthStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// MockPasswordStore is a mock of PasswordStore interface.
type MockPasswordStore struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordStoreMockRecorder
	isgomock struct{}
}

// MockPasswordStoreMockRecorder is the mock recorder for MockPasswordStore.
type MockPasswordStoreMockRecorder struct {
	mock *MockPasswordStore
}

// NewMockPasswordStore creates a new mock instance.
func NewMockPasswordStore(ctrl *gomock.Controller) *MockPasswordStore {
	mock := &MockPasswordStore{ctrl: ctrl}
	mock.recorder = &MockPasswordStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordStore) EXPECT() *MockPasswordStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockPasswordStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockPasswordStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockPasswordStore)(nil).DestroySession), ctx, sessionID)
}

// NewSession mocks base method.
func (m *MockPasswordStore) NewSession(ctx context.Context, username string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockPasswordStoreMockRecorder) NewSession(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockPasswordStore)(nil).NewSession), ctx, username)
}

// Session mocks base method.
func (m *MockPasswordStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockPasswordStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockPasswordStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockPasswordStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockPasswordStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockPasswordStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockPasswordStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockPasswordStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockPasswordStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockPasswordStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockPasswordStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockPasswordStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// UpdateUserPasswordHash mocks base method.
func (m *MockPasswordStore) UpdateUserPasswordHash(ctx context.Context, id ccc.UUID, hash *securehash.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordHash indicates an expected call of UpdateUserPasswordHash.
func (mr *MockPasswordStoreMockRecorder) UpdateUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordHash", reflect.TypeOf((*MockPasswordStore)(nil).UpdateUserPasswordHash), ctx, id, hash)
}

// User mocks base method.
func (m *MockPasswordStore) User(ctx context.Context, id ccc.UUID) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockPasswordStoreMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockPasswordStore)(nil).User), ctx, id)
}

// UserByUserName mocks base method.
func (m *MockPasswordStore) UserByUserName(ctx context.Context, username string) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUserName", ctx, username)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUserName indicates an expected call of UserByUserName.
func (mr *MockPasswordStoreMockRecorder) UserByUserName(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUserName", reflect.TypeOf((*MockPasswordStore)(nil).UserByUserName), ctx, username)
}

// MockOIDCStore is a mock of OIDCStore interface.
type MockOIDCStore struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCStoreMockRecorder
	isgomock struct{}
}

// MockOIDCStoreMockRecorder is the mock recorder for MockOIDCStore.
type MockOIDCStoreMockRecorder struct {
	mock *MockOIDCStore
}

// NewMockOIDCStore creates a new mock instance.
func NewMockOIDCStore(ctrl *gomock.Controller) *MockOIDCStore {
	mock := &MockOIDCStore{ctrl: ctrl}
	mock.recorder = &MockOIDCStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCStore) EXPECT() *MockOIDCStoreMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *MockOIDCStore) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockOIDCStoreMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockOIDCStore)(nil).DestroySession), ctx, sessionID)
}

// DestroySessionOIDC mocks base method.
func (m *MockOIDCStore) DestroySessionOIDC(ctx context.Context, oidcSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySessionOIDC", ctx, oidcSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySessionOIDC indicates an expected call of DestroySessionOIDC.
func (mr *MockOIDCStoreMockRecorder) DestroySessionOIDC(ctx, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySessionOIDC", reflect.TypeOf((*MockOIDCStore)(nil).DestroySessionOIDC), ctx, oidcSID)
}

// NewSession mocks base method.
func (m *MockOIDCStore) NewSession(ctx context.Context, username, oidcSID string) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, username, oidcSID)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockOIDCStoreMockRecorder) NewSession(ctx, username, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockOIDCStore)(nil).NewSession), ctx, username, oidcSID)
}

// Session mocks base method.
func (m *MockOIDCStore) Session(ctx context.Context, sessionID ccc.UUID) (*sessioninfo.SessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*sessioninfo.SessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockOIDCStoreMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockOIDCStore)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *MockOIDCStore) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockOIDCStoreMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*MockOIDCStore)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *MockOIDCStore) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockOIDCStoreMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*MockOIDCStore)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *MockOIDCStore) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockOIDCStoreMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockOIDCStore)(nil).UpdateSessionActivity), ctx, sessionID)
}

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
	isgomock struct{}
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// DestroySession mocks base method.
func (m *Mockdb) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockdbMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*Mockdb)(nil).DestroySession), ctx, sessionID)
}

// DestroySessionOIDC mocks base method.
func (m *Mockdb) DestroySessionOIDC(ctx context.Context, oidcSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySessionOIDC", ctx, oidcSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySessionOIDC indicates an expected call of DestroySessionOIDC.
func (mr *MockdbMockRecorder) DestroySessionOIDC(ctx, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySessionOIDC", reflect.TypeOf((*Mockdb)(nil).DestroySessionOIDC), ctx, oidcSID)
}

// InsertSession mocks base method.
func (m *Mockdb) InsertSession(ctx context.Context, session *dbtype.InsertSession) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, session)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockdbMockRecorder) InsertSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*Mockdb)(nil).InsertSession), ctx, session)
}

// InsertSessionOIDC mocks base method.
func (m *Mockdb) InsertSessionOIDC(ctx context.Context, session *dbtype.InsertOIDCSession) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSessionOIDC", ctx, session)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSessionOIDC indicates an expected call of InsertSessionOIDC.
func (mr *MockdbMockRecorder) InsertSessionOIDC(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSessionOIDC", reflect.TypeOf((*Mockdb)(nil).InsertSessionOIDC), ctx, session)
}

// Session mocks base method.
func (m *Mockdb) Session(ctx context.Context, sessionID ccc.UUID) (*dbtype.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*dbtype.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockdbMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*Mockdb)(nil).Session), ctx, sessionID)
}

// SetSessionTableName mocks base method.
func (m *Mockdb) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockdbMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*Mockdb)(nil).SetSessionTableName), name)
}

// SetUserTableName mocks base method.
func (m *Mockdb) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockdbMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*Mockdb)(nil).SetUserTableName), name)
}

// UpdateSessionActivity mocks base method.
func (m *Mockdb) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockdbMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*Mockdb)(nil).UpdateSessionActivity), ctx, sessionID)
}

// UpdateUserPasswordHash mocks base method.
func (m *Mockdb) UpdateUserPasswordHash(ctx context.Context, id ccc.UUID, hash *securehash.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordHash indicates an expected call of UpdateUserPasswordHash.
func (mr *MockdbMockRecorder) UpdateUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordHash", reflect.TypeOf((*Mockdb)(nil).UpdateUserPasswordHash), ctx, id, hash)
}

// User mocks base method.
func (m *Mockdb) User(ctx context.Context, id ccc.UUID) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockdbMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*Mockdb)(nil).User), ctx, id)
}

// UserByUserName mocks base method.
func (m *Mockdb) UserByUserName(ctx context.Context, username string) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUserName", ctx, username)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUserName indicates an expected call of UserByUserName.
func (mr *MockdbMockRecorder) UserByUserName(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUserName", reflect.TypeOf((*Mockdb)(nil).UserByUserName), ctx, username)
}
