// Code generated by MockGen. DO NOT EDIT.
// Source: ../sessionstorage/sessionstorage_iface.go
//
// Generated by this command:
//
//	mockgen -source ../sessionstorage/sessionstorage_iface.go -destination ../sessionstorage/db_mock_test.go -package sessionstorage -exclude_interfaces BaseStore,PreauthStore,PasswordAuthStore,OIDCStore,GoogleOIDCStore
//

// Package sessionstorage is a generated GoMock package.
package sessionstorage

import (
	context "context"
	reflect "reflect"

	ccc "github.com/cccteam/ccc"
	securehash "github.com/cccteam/ccc/securehash"
	dbtype "github.com/cccteam/session/internal/dbtype"
	sessioninfo "github.com/cccteam/session/sessioninfo"
	gomock "go.uber.org/mock/gomock"
)

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
	isgomock struct{}
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *Mockdb) ActivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockdbMockRecorder) ActivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*Mockdb)(nil).ActivateUser), ctx, id)
}

// CreateUser mocks base method.
func (m *Mockdb) CreateUser(ctx context.Context, insertSessionUser *dbtype.InsertSessionUser, customData any) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, insertSessionUser, customData)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockdbMockRecorder) CreateUser(ctx, insertSessionUser, customData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Mockdb)(nil).CreateUser), ctx, insertSessionUser, customData)
}

// CustomDataType mocks base method.
func (m *Mockdb) CustomDataType() reflect.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomDataType")
	ret0, _ := ret[0].(reflect.Type)
	return ret0
}

// CustomDataType indicates an expected call of CustomDataType.
func (mr *MockdbMockRecorder) CustomDataType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomDataType", reflect.TypeOf((*Mockdb)(nil).CustomDataType))
}

// CustomUserData mocks base method.
func (m *Mockdb) CustomUserData(ctx context.Context, userID ccc.UUID) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomUserData", ctx, userID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomUserData indicates an expected call of CustomUserData.
func (mr *MockdbMockRecorder) CustomUserData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomUserData", reflect.TypeOf((*Mockdb)(nil).CustomUserData), ctx, userID)
}

// CustomUserDataType mocks base method.
func (m *Mockdb) CustomUserDataType() reflect.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomUserDataType")
	ret0, _ := ret[0].(reflect.Type)
	return ret0
}

// CustomUserDataType indicates an expected call of CustomUserDataType.
func (mr *MockdbMockRecorder) CustomUserDataType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomUserDataType", reflect.TypeOf((*Mockdb)(nil).CustomUserDataType))
}

// DeactivateUser mocks base method.
func (m *Mockdb) DeactivateUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockdbMockRecorder) DeactivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*Mockdb)(nil).DeactivateUser), ctx, id)
}

// DeleteUser mocks base method.
func (m *Mockdb) DeleteUser(ctx context.Context, id ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockdbMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*Mockdb)(nil).DeleteUser), ctx, id)
}

// DestroyAllUserSessions mocks base method.
func (m *Mockdb) DestroyAllUserSessions(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyAllUserSessions", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyAllUserSessions indicates an expected call of DestroyAllUserSessions.
func (mr *MockdbMockRecorder) DestroyAllUserSessions(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyAllUserSessions", reflect.TypeOf((*Mockdb)(nil).DestroyAllUserSessions), ctx, username)
}

// DestroySession mocks base method.
func (m *Mockdb) DestroySession(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockdbMockRecorder) DestroySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*Mockdb)(nil).DestroySession), ctx, sessionID)
}

// DestroySessionOIDC mocks base method.
func (m *Mockdb) DestroySessionOIDC(ctx context.Context, oidcSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySessionOIDC", ctx, oidcSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySessionOIDC indicates an expected call of DestroySessionOIDC.
func (mr *MockdbMockRecorder) DestroySessionOIDC(ctx, oidcSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySessionOIDC", reflect.TypeOf((*Mockdb)(nil).DestroySessionOIDC), ctx, oidcSID)
}

// GoogleOIDCUser mocks base method.
func (m *Mockdb) GoogleOIDCUser(ctx context.Context, id ccc.UUID) (*dbtype.GoogleOIDCUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleOIDCUser", ctx, id)
	ret0, _ := ret[0].(*dbtype.GoogleOIDCUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleOIDCUser indicates an expected call of GoogleOIDCUser.
func (mr *MockdbMockRecorder) GoogleOIDCUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleOIDCUser", reflect.TypeOf((*Mockdb)(nil).GoogleOIDCUser), ctx, id)
}

// GoogleOIDCUserBySub mocks base method.
func (m *Mockdb) GoogleOIDCUserBySub(ctx context.Context, sub string) (*dbtype.GoogleOIDCUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleOIDCUserBySub", ctx, sub)
	ret0, _ := ret[0].(*dbtype.GoogleOIDCUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleOIDCUserBySub indicates an expected call of GoogleOIDCUserBySub.
func (mr *MockdbMockRecorder) GoogleOIDCUserBySub(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleOIDCUserBySub", reflect.TypeOf((*Mockdb)(nil).GoogleOIDCUserBySub), ctx, sub)
}

// InsertSession mocks base method.
func (m *Mockdb) InsertSession(ctx context.Context, insertSession *dbtype.InsertSession, req *sessioninfo.NewSessionRequest) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, insertSession, req)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockdbMockRecorder) InsertSession(ctx, insertSession, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*Mockdb)(nil).InsertSession), ctx, insertSession, req)
}

// InsertSessionGoogleOIDC mocks base method.
func (m *Mockdb) InsertSessionGoogleOIDC(ctx context.Context, session *dbtype.InsertSession, req *sessioninfo.NewSessionRequest) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSessionGoogleOIDC", ctx, session, req)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSessionGoogleOIDC indicates an expected call of InsertSessionGoogleOIDC.
func (mr *MockdbMockRecorder) InsertSessionGoogleOIDC(ctx, session, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSessionGoogleOIDC", reflect.TypeOf((*Mockdb)(nil).InsertSessionGoogleOIDC), ctx, session, req)
}

// InsertSessionOIDC mocks base method.
func (m *Mockdb) InsertSessionOIDC(ctx context.Context, session *dbtype.InsertOIDCSession, req *sessioninfo.NewSessionRequest) (ccc.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSessionOIDC", ctx, session, req)
	ret0, _ := ret[0].(ccc.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSessionOIDC indicates an expected call of InsertSessionOIDC.
func (mr *MockdbMockRecorder) InsertSessionOIDC(ctx, session, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSessionOIDC", reflect.TypeOf((*Mockdb)(nil).InsertSessionOIDC), ctx, session, req)
}

// OIDCUser mocks base method.
func (m *Mockdb) OIDCUser(ctx context.Context, id ccc.UUID) (*dbtype.OIDCUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCUser", ctx, id)
	ret0, _ := ret[0].(*dbtype.OIDCUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OIDCUser indicates an expected call of OIDCUser.
func (mr *MockdbMockRecorder) OIDCUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCUser", reflect.TypeOf((*Mockdb)(nil).OIDCUser), ctx, id)
}

// OIDCUserByKey mocks base method.
func (m *Mockdb) OIDCUserByKey(ctx context.Context, tid, oid string) (*dbtype.OIDCUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCUserByKey", ctx, tid, oid)
	ret0, _ := ret[0].(*dbtype.OIDCUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OIDCUserByKey indicates an expected call of OIDCUserByKey.
func (mr *MockdbMockRecorder) OIDCUserByKey(ctx, tid, oid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCUserByKey", reflect.TypeOf((*Mockdb)(nil).OIDCUserByKey), ctx, tid, oid)
}

// OIDCUsersEnabled mocks base method.
func (m *Mockdb) OIDCUsersEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OIDCUsersEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// OIDCUsersEnabled indicates an expected call of OIDCUsersEnabled.
func (mr *MockdbMockRecorder) OIDCUsersEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OIDCUsersEnabled", reflect.TypeOf((*Mockdb)(nil).OIDCUsersEnabled))
}

// Session mocks base method.
func (m *Mockdb) Session(ctx context.Context, sessionID ccc.UUID) (*dbtype.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, sessionID)
	ret0, _ := ret[0].(*dbtype.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockdbMockRecorder) Session(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*Mockdb)(nil).Session), ctx, sessionID)
}

// SetOIDCUserTableName mocks base method.
func (m *Mockdb) SetOIDCUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOIDCUserTableName", name)
}

// SetOIDCUserTableName indicates an expected call of SetOIDCUserTableName.
func (mr *MockdbMockRecorder) SetOIDCUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOIDCUserTableName", reflect.TypeOf((*Mockdb)(nil).SetOIDCUserTableName), name)
}

// SetSessionTableName mocks base method.
func (m *Mockdb) SetSessionTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSessionTableName", name)
}

// SetSessionTableName indicates an expected call of SetSessionTableName.
func (mr *MockdbMockRecorder) SetSessionTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTableName", reflect.TypeOf((*Mockdb)(nil).SetSessionTableName), name)
}

// SetUserPasswordHash mocks base method.
func (m *Mockdb) SetUserPasswordHash(ctx context.Context, id ccc.UUID, hash *securehash.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserPasswordHash indicates an expected call of SetUserPasswordHash.
func (mr *MockdbMockRecorder) SetUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPasswordHash", reflect.TypeOf((*Mockdb)(nil).SetUserPasswordHash), ctx, id, hash)
}

// SetUserTableName mocks base method.
func (m *Mockdb) SetUserTableName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserTableName", name)
}

// SetUserTableName indicates an expected call of SetUserTableName.
func (mr *MockdbMockRecorder) SetUserTableName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserTableName", reflect.TypeOf((*Mockdb)(nil).SetUserTableName), name)
}

// SetUserUsername mocks base method.
func (m *Mockdb) SetUserUsername(ctx context.Context, id ccc.UUID, newUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserUsername", ctx, id, newUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserUsername indicates an expected call of SetUserUsername.
func (mr *MockdbMockRecorder) SetUserUsername(ctx, id, newUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserUsername", reflect.TypeOf((*Mockdb)(nil).SetUserUsername), ctx, id, newUsername)
}

// UpdateCustomSessionData mocks base method.
func (m *Mockdb) UpdateCustomSessionData(ctx context.Context, sessionID ccc.UUID, mutate func(any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomSessionData", ctx, sessionID, mutate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomSessionData indicates an expected call of UpdateCustomSessionData.
func (mr *MockdbMockRecorder) UpdateCustomSessionData(ctx, sessionID, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomSessionData", reflect.TypeOf((*Mockdb)(nil).UpdateCustomSessionData), ctx, sessionID, mutate)
}

// UpdateCustomUserData mocks base method.
func (m *Mockdb) UpdateCustomUserData(ctx context.Context, userID ccc.UUID, mutate func(any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomUserData", ctx, userID, mutate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomUserData indicates an expected call of UpdateCustomUserData.
func (mr *MockdbMockRecorder) UpdateCustomUserData(ctx, userID, mutate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomUserData", reflect.TypeOf((*Mockdb)(nil).UpdateCustomUserData), ctx, userID, mutate)
}

// UpdateSessionActivity mocks base method.
func (m *Mockdb) UpdateSessionActivity(ctx context.Context, sessionID ccc.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockdbMockRecorder) UpdateSessionActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*Mockdb)(nil).UpdateSessionActivity), ctx, sessionID)
}

// User mocks base method.
func (m *Mockdb) User(ctx context.Context, id ccc.UUID) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockdbMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*Mockdb)(nil).User), ctx, id)
}

// UserByUserName mocks base method.
func (m *Mockdb) UserByUserName(ctx context.Context, username string) (*dbtype.SessionUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUserName", ctx, username)
	ret0, _ := ret[0].(*dbtype.SessionUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByUserName indicates an expected call of UserByUserName.
func (mr *MockdbMockRecorder) UserByUserName(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUserName", reflect.TypeOf((*Mockdb)(nil).UserByUserName), ctx, username)
}

// UserDataLoginHookConfigured mocks base method.
func (m *Mockdb) UserDataLoginHookConfigured() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDataLoginHookConfigured")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UserDataLoginHookConfigured indicates an expected call of UserDataLoginHookConfigured.
func (mr *MockdbMockRecorder) UserDataLoginHookConfigured() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDataLoginHookConfigured", reflect.TypeOf((*Mockdb)(nil).UserDataLoginHookConfigured))
}
