// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/cookie/cookie_iface.go
//
// Generated by this command:
//
//	mockgen -source ../internal/cookie/cookie_iface.go -destination mock_cookie/mock_cookie_iface.go
//

// Package mock_cookie is a generated GoMock package.
package mock_cookie

import (
	http "net/http"
	reflect "reflect"
	time "time"

	ccc "github.com/cccteam/ccc"
	types "github.com/cccteam/session/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCookieManager is a mock of CookieManager interface.
type MockCookieManager struct {
	ctrl     *gomock.Controller
	recorder *MockCookieManagerMockRecorder
	isgomock struct{}
}

// MockCookieManagerMockRecorder is the mock recorder for MockCookieManager.
type MockCookieManagerMockRecorder struct {
	mock *MockCookieManager
}

// NewMockCookieManager creates a new mock instance.
func NewMockCookieManager(ctrl *gomock.Controller) *MockCookieManager {
	mock := &MockCookieManager{ctrl: ctrl}
	mock.recorder = &MockCookieManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookieManager) EXPECT() *MockCookieManagerMockRecorder {
	return m.recorder
}

// HasValidXSRFToken mocks base method.
func (m *MockCookieManager) HasValidXSRFToken(r *http.Request) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasValidXSRFToken", r)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasValidXSRFToken indicates an expected call of HasValidXSRFToken.
func (mr *MockCookieManagerMockRecorder) HasValidXSRFToken(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasValidXSRFToken", reflect.TypeOf((*MockCookieManager)(nil).HasValidXSRFToken), r)
}

// NewAuthCookie mocks base method.
func (m *MockCookieManager) NewAuthCookie(w http.ResponseWriter, sameSiteStrict bool, sessionID ccc.UUID) (map[types.SCKey]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAuthCookie", w, sameSiteStrict, sessionID)
	ret0, _ := ret[0].(map[types.SCKey]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAuthCookie indicates an expected call of NewAuthCookie.
func (mr *MockCookieManagerMockRecorder) NewAuthCookie(w, sameSiteStrict, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthCookie", reflect.TypeOf((*MockCookieManager)(nil).NewAuthCookie), w, sameSiteStrict, sessionID)
}

// ReadAuthCookie mocks base method.
func (m *MockCookieManager) ReadAuthCookie(r *http.Request) (map[types.SCKey]string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAuthCookie", r)
	ret0, _ := ret[0].(map[types.SCKey]string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ReadAuthCookie indicates an expected call of ReadAuthCookie.
func (mr *MockCookieManagerMockRecorder) ReadAuthCookie(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAuthCookie", reflect.TypeOf((*MockCookieManager)(nil).ReadAuthCookie), r)
}

// SetXSRFTokenCookie mocks base method.
func (m *MockCookieManager) SetXSRFTokenCookie(w http.ResponseWriter, r *http.Request, sessionID ccc.UUID, cookieExpiration time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetXSRFTokenCookie", w, r, sessionID, cookieExpiration)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetXSRFTokenCookie indicates an expected call of SetXSRFTokenCookie.
func (mr *MockCookieManagerMockRecorder) SetXSRFTokenCookie(w, r, sessionID, cookieExpiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXSRFTokenCookie", reflect.TypeOf((*MockCookieManager)(nil).SetXSRFTokenCookie), w, r, sessionID, cookieExpiration)
}

// WriteAuthCookie mocks base method.
func (m *MockCookieManager) WriteAuthCookie(w http.ResponseWriter, sameSiteStrict bool, cval map[types.SCKey]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAuthCookie", w, sameSiteStrict, cval)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAuthCookie indicates an expected call of WriteAuthCookie.
func (mr *MockCookieManagerMockRecorder) WriteAuthCookie(w, sameSiteStrict, cval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAuthCookie", reflect.TypeOf((*MockCookieManager)(nil).WriteAuthCookie), w, sameSiteStrict, cval)
}
